BRDFExplorer3000: WaitingSpinnerWidget Class Reference
WaitingSpinnerWidget Class Reference
#include <waitingspinnerwidget.h>
Public Slots
void start ()
void stop ()
Public Member Functions
WaitingSpinnerWidget (QWidget *parent=0, bool centerOnParent=true, bool disableParentWhenSpinning=true)
WaitingSpinnerWidget (Qt::WindowModality modality, QWidget *parent=0, bool centerOnParent=true, bool disableParentWhenSpinning=true)
void setColor (QColor color)
void setRoundness (qreal roundness)
void setMinimumTrailOpacity (qreal minimumTrailOpacity)
void setTrailFadePercentage (qreal trail)
void setRevolutionsPerSecond (qreal revolutionsPerSecond)
void setNumberOfLines (int lines)
void setLineLength (int length)
void setLineWidth (int width)
void setInnerRadius (int radius)
void setText (QString text)
QColor color ()
qreal roundness ()
qreal minimumTrailOpacity ()
qreal trailFadePercentage ()
qreal revolutionsPersSecond ()
int numberOfLines ()
int lineLength ()
int lineWidth ()
int innerRadius ()
bool isSpinning () const
Protected Member Functions
void paintEvent (QPaintEvent *paintEvent)
Private Slots
void rotate ()
Private Member Functions
void initialize ()
void updateSize ()
void updateTimer ()
void updatePosition ()
WaitingSpinnerWidget (const WaitingSpinnerWidget &)
WaitingSpinnerWidget & operator= (const WaitingSpinnerWidget &)
Static Private Member Functions
static int lineCountDistanceFromPrimary (int current, int primary, int totalNrOfLines)
static QColor currentLineColor (int distance, int totalNrOfLines, qreal trailFadePerc, qreal minOpacity, QColor color)
Private Attributes
QColor _color
qreal _roundness
qreal _minimumTrailOpacity
qreal _trailFadePercentage
qreal _revolutionsPerSecond
int _numberOfLines
int _lineLength
int _lineWidth
int _innerRadius
QTimer * _timer
bool _centerOnParent
bool _disableParentWhenSpinning
int _currentCounter
bool _isSpinning
Constructor & Destructor Documentation
WaitingSpinnerWidget() [1/3]
WaitingSpinnerWidget::WaitingSpinnerWidget (QWidget * parent = 0, bool centerOnParent = true, bool disableParentWhenSpinning = true)
Constructor for "standard" widget behaviour - use this constructor if you wish to, e.g. embed your widget in another.
References initialize().
WaitingSpinnerWidget() [2/3]
WaitingSpinnerWidget::WaitingSpinnerWidget (Qt::WindowModality modality, QWidget * parent = 0, bool centerOnParent = true, bool disableParentWhenSpinning = true)
Constructor - use this constructor to automatically create a modal ("blocking") spinner on top of the calling widget/window. If a valid parent widget is provided, "centreOnParent" will ensure that QtWaitingSpinner automatically centres itself on it, if not, "centreOnParent" is ignored.
References initialize().
WaitingSpinnerWidget() [3/3]
WaitingSpinnerWidget::WaitingSpinnerWidget (const WaitingSpinnerWidget &) private
Member Function Documentation
color()
QColor WaitingSpinnerWidget::color ()
References _color.
currentLineColor()
QColor WaitingSpinnerWidget::currentLineColor (int distance, int totalNrOfLines, qreal trailFadePerc, qreal minOpacity, QColor color) static private
References color().
initialize()
void WaitingSpinnerWidget::initialize () private
References _color, _currentCounter, _innerRadius, _isSpinning, _lineLength, _lineWidth, _minimumTrailOpacity, _numberOfLines, _revolutionsPerSecond, _roundness, _timer, _trailFadePercentage, rotate(), updateSize(), and updateTimer().
innerRadius()
int WaitingSpinnerWidget::innerRadius ()
References _innerRadius.
isSpinning()
bool WaitingSpinnerWidget::isSpinning () const
References _isSpinning.
lineCountDistanceFromPrimary()
int WaitingSpinnerWidget::lineCountDistanceFromPrimary (int current, int primary, int totalNrOfLines) static private
lineLength()
int WaitingSpinnerWidget::lineLength ()
References _lineLength.
lineWidth()
int WaitingSpinnerWidget::lineWidth ()
References _lineWidth.
minimumTrailOpacity()
qreal WaitingSpinnerWidget::minimumTrailOpacity ()
References _minimumTrailOpacity.
numberOfLines()
int WaitingSpinnerWidget::numberOfLines ()
References _numberOfLines.
operator=()
WaitingSpinnerWidget& WaitingSpinnerWidget::operator= (const WaitingSpinnerWidget &) private
paintEvent()
void WaitingSpinnerWidget::paintEvent (QPaintEvent * paintEvent) protected
References _color, _currentCounter, _innerRadius, _lineLength, _lineWidth, _minimumTrailOpacity, _numberOfLines, _roundness, _trailFadePercentage, color(), currentLineColor(), lineCountDistanceFromPrimary(), and updatePosition().
revolutionsPersSecond()
qreal WaitingSpinnerWidget::revolutionsPersSecond ()
References _revolutionsPerSecond.
rotate
void WaitingSpinnerWidget::rotate () private slot
References _currentCounter, and _numberOfLines.
roundness()
qreal WaitingSpinnerWidget::roundness ()
References _roundness.
setColor()
void WaitingSpinnerWidget::setColor (QColor color)
References _color, and color().
setInnerRadius()
void WaitingSpinnerWidget::setInnerRadius (int radius)
References _innerRadius, and updateSize().
setLineLength()
void WaitingSpinnerWidget::setLineLength (int length)
References _lineLength, and updateSize().
setLineWidth()
void WaitingSpinnerWidget::setLineWidth (int width)
References _lineWidth, and updateSize().
setMinimumTrailOpacity()
void WaitingSpinnerWidget::setMinimumTrailOpacity (qreal minimumTrailOpacity)
References _minimumTrailOpacity, and minimumTrailOpacity().
setNumberOfLines()
void WaitingSpinnerWidget::setNumberOfLines (int lines)
References _currentCounter, _numberOfLines, and updateTimer().
setRevolutionsPerSecond()
void WaitingSpinnerWidget::setRevolutionsPerSecond (qreal revolutionsPerSecond)
References _revolutionsPerSecond, and updateTimer().
setRoundness()
void WaitingSpinnerWidget::setRoundness (qreal roundness)
References _roundness, and roundness().
setText()
void WaitingSpinnerWidget::setText (QString text)
setTrailFadePercentage()
void WaitingSpinnerWidget::setTrailFadePercentage (qreal trail)
References _trailFadePercentage.
start
void WaitingSpinnerWidget::start () slot
References _currentCounter, _disableParentWhenSpinning, _isSpinning, _timer, and updatePosition().
stop
void WaitingSpinnerWidget::stop () slot
References _currentCounter, _disableParentWhenSpinning, _isSpinning, and _timer.
trailFadePercentage()
qreal WaitingSpinnerWidget::trailFadePercentage ()
References _trailFadePercentage.
updatePosition()
void WaitingSpinnerWidget::updatePosition () private
References _centerOnParent.
updateSize()
void WaitingSpinnerWidget::updateSize () private
References _innerRadius, and _lineLength.
updateTimer()
void WaitingSpinnerWidget::updateTimer () private
References _numberOfLines, _revolutionsPerSecond, and _timer.
Member Data Documentation
_centerOnParent
bool WaitingSpinnerWidget::_centerOnParent private
_color
QColor WaitingSpinnerWidget::_color private
_currentCounter
int WaitingSpinnerWidget::_currentCounter private
_disableParentWhenSpinning
bool WaitingSpinnerWidget::_disableParentWhenSpinning private
_innerRadius
int WaitingSpinnerWidget::_innerRadius private
_isSpinning
bool WaitingSpinnerWidget::_isSpinning private
_lineLength
int WaitingSpinnerWidget::_lineLength private
_lineWidth
int WaitingSpinnerWidget::_lineWidth private
_minimumTrailOpacity
qreal WaitingSpinnerWidget::_minimumTrailOpacity private
_numberOfLines
int WaitingSpinnerWidget::_numberOfLines private
_revolutionsPerSecond
qreal WaitingSpinnerWidget::_revolutionsPerSecond private
_roundness
qreal WaitingSpinnerWidget::_roundness private
_timer
QTimer* WaitingSpinnerWidget::_timer private
_trailFadePercentage
qreal WaitingSpinnerWidget::_trailFadePercentage private
The documentation for this class was generated from the following files:
waitingspinnerwidget.h
waitingspinnerwidget.cpp