BRDFExplorer3000: ChefDevr::WaitingDisplay Class Reference
ChefDevr::WaitingDisplay Class Reference
#include <WaitingDisplay.h>
Public Member Functions
WaitingDisplay ()
Constructor & Destructor Documentation
WaitingDisplay()
ChefDevr::WaitingDisplay::WaitingDisplay ()
References WaitingSpinnerWidget::setColor(), WaitingSpinnerWidget::setInnerRadius(), WaitingSpinnerWidget::setLineLength(), WaitingSpinnerWidget::setLineWidth(), WaitingSpinnerWidget::setMinimumTrailOpacity(), WaitingSpinnerWidget::setNumberOfLines(), WaitingSpinnerWidget::setRevolutionsPerSecond(), WaitingSpinnerWidget::setRoundness(), WaitingSpinnerWidget::setTrailFadePercentage(), and WaitingSpinnerWidget::start().
The documentation for this class was generated from the following files:
WaitingDisplay.h
WaitingDisplay.cpp